language: scala

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

scala:
   - 2.11.7


script:
   - sbt ++$TRAVIS_SCALA_VERSION test
   - sbt docker:publish

   # Tricks to avoid unnecessary cache updates
   - find $HOME/.sbt -name "*.lock" | xargs rm
   - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
   - sbt ++$TRAVIS_SCALA_VERSION docker:publish

jdk:
   - oraclejdk8
