language: scala

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

install:
    - curl -sLo - http://j.mp/install-travis-docker | sh -xe

scala:
   - 2.11.7


script:
   - sbt ++$TRAVIS_SCALA_VERSION test
   - sbt docker:publishLocal

   # Tricks to avoid unnecessary cache updates
   - find $HOME/.sbt -name "*.lock" | xargs rm
   - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
   - sbt ++$TRAVIS_SCALA_VERSION docker:publish

jdk:
   - oraclejdk8
